#!/usr/bin/env python3
"""Generate ios/ChinGo/Resources/chingo-style.json.

The style is DERIVED, not hand-written. A basemap style is 119 layers of filters and zoom
interpolations that took people years to get right; hand-rolling a dozen of them produces a
map that silently renders nothing, which is exactly what happened on the first attempt.

So: take OpenFreeMap's `bright` style, which is known to work against their tiles, and
repaint every colour through the Ink palette. Geometry, filters and zoom curves are left
completely alone. Buildings gain a fill-extrusion layer so a city reads as a place rather
than a floor plan.

Re-run after changing the palette:  python3 scripts/build-style.py
"""

import json
import urllib.request
from pathlib import Path

SOURCE_STYLE = "https://tiles.openfreemap.org/styles/bright"
OUT = Path(__file__).resolve().parent.parent / "ios/ChinGo/Resources/chingo-style.json"

# Mirrors ChinGoDesign/Sources/ChinGoDesign/Palette.swift. The map and the chrome floating
# over it have to be one product, so these two files change together.
INK = {
    "land":          "#EDE7D6",
    "land_alt":      "#E9E2CF",
    "park":          "#CFE0BC",
    "water":         "#A8D8D0",
    "road":          "#FFFDF7",
    "road_casing":   "#DDD5C2",
    "road_minor":    "#F7F2E4",
    "building":      "#F2EBDA",
    "building_warm": "#EADEC8",
    "building_side": "#DCCDB2",
    "text":          "#6B655A",
    "text_faint":    "#A39C8D",
    "halo":          "#F6F2E7",
}

GREEN_LAYERS = ("park", "landcover", "wood", "grass", "forest", "golf", "pitch", "cemetery")
WATER_LAYERS = ("water", "waterway", "ocean", "river", "lake")


def repaint(layer: dict) -> dict:
    """Repaint one layer. Geometry, filters and zoom stops are never touched."""
    lid = layer.get("id", "")
    src_layer = layer.get("source-layer", "")
    kind = layer.get("type")
    paint = layer.setdefault("paint", {})
    tag = f"{lid} {src_layer}".lower()

    def flat(key: str, colour: str) -> None:
        """Replace a colour outright, discarding any data-driven expression.

        Deliberate: the whole look depends on the map being flat, quiet colour that the
        interface can sit on top of. A basemap that keeps its own colour ramps competes with
        the cards floating above it.
        """
        if key in paint or kind in ("fill", "line", "background"):
            paint[key] = colour

    if kind == "background":
        flat("background-color", INK["land"])

    elif kind == "fill":
        if any(w in tag for w in WATER_LAYERS):
            flat("fill-color", INK["water"])
        elif any(g in tag for g in GREEN_LAYERS):
            flat("fill-color", INK["park"])
        elif "building" in tag:
            # Flat footprints are hidden; the extrusion layer added below replaces them.
            paint["fill-opacity"] = 0
        elif "landuse" in tag or "landcover" in tag:
            flat("fill-color", INK["land_alt"])
        else:
            flat("fill-color", INK["land_alt"])
        paint.pop("fill-outline-color", None)

    elif kind == "line":
        if any(w in tag for w in WATER_LAYERS):
            flat("line-color", INK["water"])
        elif "casing" in tag or "bridge" in tag and "casing" in tag:
            flat("line-color", INK["road_casing"])
        elif "boundary" in tag or "admin" in tag:
            flat("line-color", INK["text_faint"])
        elif "building" in tag:
            paint["line-opacity"] = 0
        else:
            flat("line-color", INK["road"])

    elif kind == "symbol":
        paint["text-color"] = INK["text"]
        paint["text-halo-color"] = INK["halo"]
        paint["text-halo-width"] = 1.4
        paint.pop("icon-color", None)
        # Drop the sprite pictograms entirely. They arrive in the source style's own colours
        # -- bright blue transit badges, green park markers -- which fight a flat palette and
        # compete with the cards floating above the map. Names stay, symbols go.
        layout = layer.setdefault("layout", {})
        layout.pop("icon-image", None)
        layout.pop("icon-size", None)

    elif kind == "raster":
        # The shaded-relief raster underlay fights a flat palette.
        paint["raster-opacity"] = 0

    return layer


def main() -> None:
    # An explicit User-Agent is required: the CDN answers urllib's default with 403.
    request = urllib.request.Request(
        SOURCE_STYLE, headers={"User-Agent": "chingo-style-builder/1.0"}
    )
    with urllib.request.urlopen(request, timeout=60) as response:
        style = json.load(response)

    style["name"] = "ChinGo"
    style["metadata"] = {
        "chingo:generated": (
            "Generated by scripts/build-style.py from OpenFreeMap's `bright` style. Do not "
            "edit by hand -- change the palette in the script and regenerate, or the next "
            "regeneration silently discards the edit."
        )
    }

    layers = []
    for layer in style.get("layers", []):
        lid = layer.get("id", "").lower()
        # Icon-only POI markers are visual noise under floating cards, and every one of them
        # is a sprite lookup. Named places stay; pictograms go.
        if "poi" in lid and layer.get("type") == "symbol":
            layout = layer.get("layout", {})
            if "text-field" not in layout:
                continue
        layers.append(repaint(layer))

    # Buildings, extruded. On a raked camera a flat footprint reads as paint on the road;
    # a solid with height reads as a city. Height falls back through the OpenMapTiles
    # convention: a real height tag, else storeys x 3.66m, else a flat 5m.
    building_index = next(
        (i for i, l in enumerate(layers) if l.get("source-layer") == "building"),
        len(layers),
    )
    layers.insert(building_index, {
        "id": "chingo-building-3d",
        "type": "fill-extrusion",
        "source": "openmaptiles",
        "source-layer": "building",
        "minzoom": 14,
        "filter": ["!=", ["get", "hide_3d"], True],
        "paint": {
            "fill-extrusion-color": [
                "interpolate", ["linear"], ["coalesce", ["get", "render_height"], 5],
                0, INK["building"],
                14, INK["building_warm"],
                60, INK["building_side"],
            ],
            # Height is data-driven with no zoom term -- but not because MapLibre would
            # reject one. An earlier comment here blamed a zoom-interpolate with a
            # data-expression output for the buildings vanishing, and that was wrong: MapLibre
            # 6.29 renders exactly that shape, and the client wraps this in one at runtime to
            # clamp height up close (MapStyle.swift). What actually drops a layer silently is
            # an UNRECOGNISED PAINT KEY. Adding the Mapbox-only `fill-extrusion-rounded-roof`
            # made every building vanish with nothing in the log and no style error. A typo in
            # a paint key is invisible, not loud.
            #
            # Height stays flat here so the zoom clamp has one owner. If it ever moves into
            # this file, delete the MapStyle transform rather than fighting it.
            "fill-extrusion-height": [
                "case", ["has", "render_height"], ["get", "render_height"], 5,
            ],
            "fill-extrusion-base": [
                "case", ["has", "render_min_height"], ["get", "render_min_height"], 0,
            ],
            # Fade the solids in rather than having a city snap into existence at z14.
            "fill-extrusion-opacity": [
                "interpolate", ["linear"], ["zoom"], 14, 0, 15.5, 0.95,
            ],
            # MapLibre darkens side faces automatically to fake lighting. On a warm, flat
            # palette that reads as grime rather than as depth -- the whole city goes muddy.
            # Turned off; height is legible from silhouette and the colour ramp alone.
            "fill-extrusion-vertical-gradient": False,
        },
    })

    style["layers"] = layers
    OUT.write_text(json.dumps(style, indent=2) + "\n")
    print(f"wrote {OUT.relative_to(Path.cwd())} — {len(layers)} layers")


if __name__ == "__main__":
    main()
